## Load IRIS Dataset

In [1]:
import numpy as np
from sklearn import datasets, metrics
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
iris = datasets.load_iris()

X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state = 42)

In [5]:
X_train


array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2

## Build Model

In [3]:
model = LogisticRegression()
model.fit(X_train,Y_train)
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [4]:
expected = iris.target
predicted = model.predict(iris.data)

In [5]:
print(metrics.classification_report(expected,predicted))
print(metrics.confusion_matrix(expected,predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.98      0.92      0.95        50
          2       0.92      0.98      0.95        50

avg / total       0.97      0.97      0.97       150

[[50  0  0]
 [ 0 46  4]
 [ 0  1 49]]


In [6]:
# plt.figure(figsize=(10,10))

# def plot_decision_regions(X,y,classifier,test_idx):
#     x_min, x_max = X[:,0].min()-1, X[:,0].max()+1
#     y_min, y_max = X[:,1].min()-1, X[:,1].max()+1
#     xx,yy = np.meshgrid(np.arange(x_min,x_max,0.1),np.arange(y_min,y_max,0.1))
    
#     Z = classifier.predict(np.c_[[xx.ravel(),yy.ravel()]])
#     Z = Z.reshape(xx.shape)
    
#     plt.contourf(xx,yy,Z,alpha=0.4)
#     plt.scatter(X[:,0],X[:,1],c=y,s=20,edgecolour='k')
    

<Figure size 720x720 with 0 Axes>

## Test the Model

In [8]:
print("Prediciton for last row:{}".format(model.predict_proba(iris.data[-1:])))

Prediciton for last row:[[0.00221282 0.29636878 0.7014184 ]]


## Export Model

In [11]:
import pickle
import os

pickle.dump(model,open("iris_model.pkl",'wb'))


In [12]:
loaded_model = pickle.load(open("iris_model.pkl",'rb'))
result = loaded_model.predict_proba(iris.data[-1:])
result

array([[0.00221282, 0.29636878, 0.7014184 ]])